name: github rdp tailscale edition
on:
  workflow_dispatch:
    inputs:
      password:
        description: 'set rdp password'
        required: true
        default: 'Atay@Bna3na3#2026'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: initializing environment
        run: |
          echo "starting server deployment..."
          # تعيين كلمة المرور التي اخترتها لحساب الـ runner الحالي لتتمكن من الدخول عبر الـ RDP
          net user runneradmin "${{ github.event.inputs.password }}"

      - name: installing tailscale
        run: |
          echo "downloading tailscale..."
          invoke-webrequest -uri 'https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe' -outfile 'tailscale.exe'
          start-process -filepath "tailscale.exe" -argumentlist "/quiet" -wait
          echo "waiting for service..."
          start-sleep -seconds 15
          echo "tailscale setup complete."

      - name: authenticating tailscale
        run: |
          echo "linking to tailscale network..."
          # تم تصحيح الخيار هنا وإضافة خيار عدم قطع الاتصال بعد تسجيل خروج المستخدم (unattended) للويندوز
          & "c:\program files\tailscale\tailscale.exe" up --authkey=${{ secrets.TS_KEY }} --hostname=cloud-rdp-server --accept-routes --unattended

      - name: Keep Alive & RDP Ready
        run: |
          echo "=========================================================="
          echo "Server is live on Tailscale as: cloud-rdp-server"
          echo "User: runneradmin"
          echo "Password: ${{ github.event.inputs.password }}"
          echo "=========================================================="
          # هذا الأمر يمنع السيرفر من الإغلاق ويجعله يعمل لمدة 6 ساعات (21600 ثانية) لتتمكن من استخدامه براحتك
          Start-Sleep -Seconds 21600
